# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='spartanchat',
  syntax='proto3',
  serialized_pb=_b('\n\nchat.proto\x12\x0bspartanchat\"\x07\n\x05\x45mpty\"J\n\x07Message\x12\n\n\x02to\x18\x01 \x01(\x0c\x12\x0e\n\x06method\x18\x02 \x01(\x0c\x12#\n\x04user\x18\x03 \x01(\x0b\x32\x15.spartanchat.UserData\"&\n\x08UserData\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x0c\n\x04note\x18\x02 \x01(\x0c\x32}\n\nChatServer\x12\x38\n\nReceiveMsg\x12\x14.spartanchat.Message\x1a\x14.spartanchat.Message\x12\x35\n\x07SendMsg\x12\x14.spartanchat.Message\x1a\x14.spartanchat.Message2\xec\x01\n\x04User\x12\x35\n\x07\x41\x64\x64User\x12\x14.spartanchat.Message\x1a\x14.spartanchat.Message\x12\x38\n\nRemoveUser\x12\x14.spartanchat.Message\x1a\x14.spartanchat.Message\x12\x36\n\x08GetUsers\x12\x14.spartanchat.Message\x1a\x14.spartanchat.Message\x12;\n\rFriendRequest\x12\x14.spartanchat.Message\x1a\x14.spartanchat.Messageb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='spartanchat.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='spartanchat.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='spartanchat.Message.to', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='spartanchat.Message.method', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='spartanchat.Message.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=110,
)


_USERDATA = _descriptor.Descriptor(
  name='UserData',
  full_name='spartanchat.UserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='spartanchat.UserData.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='spartanchat.UserData.note', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=150,
)

_MESSAGE.fields_by_name['user'].message_type = _USERDATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['UserData'] = _USERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:spartanchat.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:spartanchat.Message)
  ))
_sym_db.RegisterMessage(Message)

UserData = _reflection.GeneratedProtocolMessageType('UserData', (_message.Message,), dict(
  DESCRIPTOR = _USERDATA,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:spartanchat.UserData)
  ))
_sym_db.RegisterMessage(UserData)



_CHATSERVER = _descriptor.ServiceDescriptor(
  name='ChatServer',
  full_name='spartanchat.ChatServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=152,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveMsg',
    full_name='spartanchat.ChatServer.ReceiveMsg',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='spartanchat.ChatServer.SendMsg',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVER)

DESCRIPTOR.services_by_name['ChatServer'] = _CHATSERVER


_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='spartanchat.User',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=280,
  serialized_end=516,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='spartanchat.User.AddUser',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveUser',
    full_name='spartanchat.User.RemoveUser',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUsers',
    full_name='spartanchat.User.GetUsers',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FriendRequest',
    full_name='spartanchat.User.FriendRequest',
    index=3,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
