# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='user',
  syntax='proto3',
  serialized_pb=_b('\n\nuser.proto\x12\x04user\"\x07\n\x05\x45mpty\"\x18\n\x08UserName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x89\x01\n\x05Group\x12\'\n\x06groups\x18\x01 \x03(\x0b\x32\x17.user.Group.GroupsEntry\x1a\x15\n\x05Users\x12\x0c\n\x04user\x18\x01 \x03(\t\x1a@\n\x0bGroupsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.user.Group.Users:\x02\x38\x01\x32\x63\n\x04User\x12+\n\x07\x41\x64\x64User\x12\x0e.user.UserName\x1a\x0e.user.UserName0\x01\x12.\n\nRemoveUser\x12\x0e.user.UserName\x1a\x0e.user.UserName0\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='user.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=27,
)


_USERNAME = _descriptor.Descriptor(
  name='UserName',
  full_name='user.UserName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='user.UserName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=53,
)


_GROUP_USERS = _descriptor.Descriptor(
  name='Users',
  full_name='user.Group.Users',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='user.Group.Users.user', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=127,
)

_GROUP_GROUPSENTRY = _descriptor.Descriptor(
  name='GroupsEntry',
  full_name='user.Group.GroupsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='user.Group.GroupsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='user.Group.GroupsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=193,
)

_GROUP = _descriptor.Descriptor(
  name='Group',
  full_name='user.Group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='user.Group.groups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GROUP_USERS, _GROUP_GROUPSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=193,
)

_GROUP_USERS.containing_type = _GROUP
_GROUP_GROUPSENTRY.fields_by_name['value'].message_type = _GROUP_USERS
_GROUP_GROUPSENTRY.containing_type = _GROUP
_GROUP.fields_by_name['groups'].message_type = _GROUP_GROUPSENTRY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['UserName'] = _USERNAME
DESCRIPTOR.message_types_by_name['Group'] = _GROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.Empty)
  ))
_sym_db.RegisterMessage(Empty)

UserName = _reflection.GeneratedProtocolMessageType('UserName', (_message.Message,), dict(
  DESCRIPTOR = _USERNAME,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserName)
  ))
_sym_db.RegisterMessage(UserName)

Group = _reflection.GeneratedProtocolMessageType('Group', (_message.Message,), dict(

  Users = _reflection.GeneratedProtocolMessageType('Users', (_message.Message,), dict(
    DESCRIPTOR = _GROUP_USERS,
    __module__ = 'user_pb2'
    # @@protoc_insertion_point(class_scope:user.Group.Users)
    ))
  ,

  GroupsEntry = _reflection.GeneratedProtocolMessageType('GroupsEntry', (_message.Message,), dict(
    DESCRIPTOR = _GROUP_GROUPSENTRY,
    __module__ = 'user_pb2'
    # @@protoc_insertion_point(class_scope:user.Group.GroupsEntry)
    ))
  ,
  DESCRIPTOR = _GROUP,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.Group)
  ))
_sym_db.RegisterMessage(Group)
_sym_db.RegisterMessage(Group.Users)
_sym_db.RegisterMessage(Group.GroupsEntry)


_GROUP_GROUPSENTRY.has_options = True
_GROUP_GROUPSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='user.User',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=195,
  serialized_end=294,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='user.User.AddUser',
    index=0,
    containing_service=None,
    input_type=_USERNAME,
    output_type=_USERNAME,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveUser',
    full_name='user.User.RemoveUser',
    index=1,
    containing_service=None,
    input_type=_USERNAME,
    output_type=_USERNAME,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
